name: ig3
channels:
  - conda-forge
  - pytorch-nightly
  - nvidia
  - defaults
dependencies:
  - addict=2.4.0
  - cudatoolkit=11.1
  - ipython
  - matplotlib=3.1.3
  - networkx=2.5.1
  - pip=20.3.3
  - python=3.7
  - pytorch
  - pyyaml
  - requests=2.23.0
  - torchaudio
  - torchvision
  - transforms3d=0.3.1
  - trimesh=3.10.7
  - six=1.12.0 
  - pip:
    - gym==0.17.3
    - opencv-python==4.4.0.44
    - pillow==8.2.0
    - scipy==1.5.4
    - stable-baselines3==0.10.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.1
