env:
  initial_pos_z_offset: 0.1
  texture_randomization_freq: null
  object_randomization_freq: null
  usd_file: null

render:
  viewer_width: 1280
  viewer_height: 720
  vertical_fov: 90

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  usd_path: null #/cvgl2/u/jdwong/PAIR/iGibson3/igibson/data/ig_dataset/scenes/Rs_int/usd/Rs_int_task_cleaning_kitchen_cupboard_0_0_fixed_furniture_template.usd #null #/cvgl2/u/jdwong/PAIR/iGibson3/igibson/data/ig_dataset/scenes/Rs_int/urdf/Rs_int_best_template.usd
  clutter: false
  build_graph: true

robots:
  - type: Tiago
    obs_modalities: [rgb, scan, occupancy_grid] # [proprioception, rgb, highlight, depth, seg, ins_seg, task_obs]
    scale: 1.0
    self_collision: false
    rendering_params: null
    action_normalize: false
    action_type: continuous
    grasping_mode: sticky #physical
    rigid_trunk: false
#    default_trunk_offset: 0.365
#    default_arm_pose: diagonal30
    controller_config:
      base:
        name: DifferentialDriveController
      arm_left:
        name: JointController #InverseKinematicsController
        motor_type: position
        command_input_limits: null
        command_output_limits: null
      arm_right:
        name: JointController #InverseKinematicsController
        motor_type: position
        command_input_limits: null
        command_output_limits: null
#        kv: 2.0
      gripper_left:
        name: MultiFingerGripperController
        mode: binary
      gripper_right:
        name: MultiFingerGripperController
        mode: binary
      camera:
        name: JointController
        motor_type: position
        use_delta_commands: False
        command_input_limits: null
        command_output_limits: null

task:
  type: BehaviorTask
  activity_name: putting_away_Halloween_decorations
  activity_definition_id: 0
  activity_instance_id: 0
  online_object_sampling: false
  termination_config:
    max_steps: 500
  reward_config:
    r_potential: 1.0