env:
  online_sampling: true
  initial_pos_z_offset: 0.1
  texture_randomization_freq: null
  object_randomization_freq: null
  usd_file: null

render:
  viewer_width: 1280
  viewer_height: 720
  vertical_fov: 90

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  usd_path: /cvgl2/u/jdwong/PAIR/iGibson3/igibson/data/ig_dataset/scenes/Rs_int/urdf/Rs_int_best_template.usd
  trav_map_resolution: 0.1
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  texture_randomization: false
  object_randomization: false
  link_collision_tolerance: 0.03
  predefined_object_randomization_idx: null
  should_open_all_doors: true
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: IG
  rendering_params: null
  include_robots: true

robots:
  - type: Turtlebot
    obs_modalities: [scan, rgb, depth]
    scale: 1.0
    self_collision: false
    rendering_params: null
    action_normalize: true
    action_type: continuous
    controller_config:
      base:
        name: DifferentialDriveController

task:
  type: DummyTask #PointNavigationTask
  robot_idn: 0
  floor: 0
  initial_pos: null
  initial_ori: null
  goal_pos: null
  goal_tolerance: 0.36    # turtlebot bodywidth
  goal_in_polar: false
  path_range: [1.0, 10.0]
  visualize_goal: true
  visualize_path: false
  n_vis_waypoints: 25
  reward_type: geodesic
#  termination_config:
#    max_collisions: 500
#    max_steps: 500
#    fall_height: 0.03
#  reward_config:
#    r_potential: 1.0
#    r_collision: 0.1
#    r_pointgoal: 10.0
