name: pipeline
channels:
  - defaults
dependencies:
  - cmake=3.22.1
  - pip=22.3.1
  - python=3.8.0
  - pip:
    - bddl==3.0.0b1
    - black>=22.10.0
    - distributed>=2023.1.1
    - docker~=7.0.0
    - dvc~=3.42.0
    - dvc-gs~=3.0.1
    - fs>=2.4.16
    - jupyter>=1.0.0
    - matplotlib>=3.5.2
    - networkx>=2.8.5
    - nltk>=3.7
    - numpy>=1.22.3
    - opencv-python>=4.5.5.64
    - pillow>=9.1.0
    - py-spy>=0.3.14
    - pyyaml>=6.0
    - ruamel-yaml>=0.17.21
    - scipy>=1.8.0
    - selenium>=4.1.5
    - sshfs>=2022.6.0
    - tqdm>=4.64.0
    - trimesh>=3.12.0
prefix: C:\Users\Cem\.conda\envs\pipeline
