joints:
  offsets:
  - 270.0
  - 180.0
  - 270.0
  - 90.0
  - 180.0
  - 0.0
  - 0.0
  - 180.0
  - 270.0

  - 90.0
  - 270.0
  - 180.0
  - 270.0
  - 180.0
  - 180.0
  - 180.0
  - 0.0
  - 270.0
  signs:
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - 1.0
  - 1.0
  - -1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - -1.0
  - 1.0