# @package _global_

policy_name: va
log_path: ~/Documents/logs/va
headless: false

model:
  _target_: omnigibson.learning.policies.VisionActionILPolicy
  robot_type: ${robot.type}
  use_websocket: true
  host: 0.0.0.0
  port: 8000
  deployed_action_steps: 8
  obs_window_size: 2
  obs_output_size: 
    left_wrist: [120, 120]
    right_wrist: [120, 120]
    head: [180, 180]
  visual_obs_types: ["rgb"]
  pcd_range: ${task.pcd_range}