env:
  initial_pos_z_offset: 0.1
  texture_randomization_freq: null
  object_randomization_freq: null
  usd_file: null

render:
  viewer_width: 1280
  viewer_height: 720
  vertical_fov: 90

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  trav_map_resolution: 0.1
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  texture_randomization: false
  object_randomization: false
  link_collision_tolerance: 0.03
  predefined_object_randomization_idx: null
  should_open_all_doors: true
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: IG
  rendering_params: null
  include_robots: true

robots:
  - type: Fetch
    obs_modalities: [scan, rgb, depth]
    scale: 1.0
    self_collision: false
    rendering_params: null
    action_normalize: true
    action_type: continuous
    grasping_mode: physical
    rigid_trunk: false
    default_trunk_offset: 0.365
    default_arm_pose: diagonal30
    controller_config:
      base:
        name: DifferentialDriveController
      arm_0:
        name: InverseKinematicsController
        kv: 2.0
      gripper_0:
        name: MultiFingerGripperController
        mode: binary
      camera:
        name: JointController
        use_delta_commands: False

objects: []

task:
  type: BehaviorTask
  activity_name: putting_away_Halloween_decorations
  activity_definition_id: 0
  activity_instance_id: 0
  predefined_problem: null
  load_clutter: false
  online_object_sampling: false
  debug_object_sampling: null
  highlight_task_relevant_objects: false
  termination_config:
    max_steps: 500
  reward_config:
    r_potential: 1.0
