env:
  initial_pos_z_offset: 0.1

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  trav_map_resolution: 0.1
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: OG
  include_robots: true

robots:
  - type: Fetch
    obs_modalities: [scan, rgb, depth]
    scale: 1.0
    self_collision: false
    action_normalize: true
    action_type: continuous
    grasping_mode: physical
    rigid_trunk: false
    default_trunk_offset: 0.365
    default_arm_pose: diagonal30
    reset_joint_pos: tuck
    controller_config:
      base:
        name: DifferentialDriveController
      arm_0:
        name: InverseKinematicsController
        kv: 2.0
      gripper_0:
        name: MultiFingerGripperController
        mode: binary
      camera:
        name: JointController
        use_delta_commands: False

objects: []

task:
  type: BehaviorTask
  activity_name: make_a_military_care_package
  activity_definition_id: 0
  activity_instance_id: 0
  online_object_sampling: false
  debug_object_sampling: null
  highlight_task_relevant_objects: false
  termination_config:
    max_steps: 50000
  reward_config:
    r_potential: 1.0

scene_graph:
  egocentric: true
  full_obs: true
  only_true: true
  merge_parallel_edges: false